import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import styles from './layout.module.css'
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({subsets: ['latin']});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <header className={styles.header}>
          <Link href='/'>
            <div className={styles.logo}>
              <Image width={48} height={37} src='/bee1.png' alt="logo"/>
              <p>Edudu</p>
            </div>
          </Link>
          <nav>
            <ul className={styles.navMenu}>
              <li><Link href='/course'>Course</Link></li>
              <li><Link href='/teacher'>Teacher</Link></li>
              <li><Link href={''}>How to use</Link></li>
              <li><Link href={''}>About Us</Link></li>
            </ul>
          </nav>
          <div className={styles.userBlock}>
            <p>Sign up</p>
            <button className={styles.authBtn}>Log in</button>
          </div>
        </header>
        {children}
        </body>
    </html>
  );
}
